In [2]:
print('Hello World')

Hello World

In [3]:
import pandas as pd

def loadData(rows = 100) :
    return pd.read_csv("../Data/Data_API.csv", nrows=rows)

dataset = loadData(1000)

In [4]:
dataset.head(5)

,Smart_contract,ID_token,Transaction_hash,Seller_address,Seller_username,Buyer_address,Buyer_username,Image_url_1,Image_url_2,Image_url_3,...,Name,Description,Collection,Market,Datetime_updated,Datetime_updated_seconds,Permanent_link,Unique_id_collection,Collection_cleaned,Category
0,NaN,87094722.0,0xed9ff1c311a611e5c457ce0a49bbbb7ed55efca98842...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0xe0fb7622091e3d9ef9b438471b10b9ea88c7cf6b,NaN,https://card.godsunchained.com/?id=33&q=4,NaN,NaN,...,NaN,NaN,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '87094722.0')",Godsunchained,Games
1,NaN,73044643.0,0xbc8412594ffa7382e8306215ece5b4e041fc641b1813...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0x2c00d05ff7ffe93d77145dfe12aa56e622ae6f40,NaN,https://card.godsunchained.com/?id=79&q=4,NaN,NaN,...,NaN,NaN,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '73044643.0')",Godsunchained,Games
2,NaN,17107482.0,0x92672baf5e9e23de230dee8e57ddf443ab6d5a336341...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0xe0fb7622091e3d9ef9b438471b10b9ea88c7cf6b,NaN,https://card.godsunchained.com/?id=33&q=4,NaN,NaN,...,NaN,NaN,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '17107482.0')",Godsunchained,Games
3,NaN,82230857.0,0x3d157249e3083622c2d756f07a05caa3a76687288b32...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0x2c00d05ff7ffe93d77145dfe12aa56e622ae6f40,NaN,https://card.godsunchained.com/?id=227&q=4,NaN,NaN,...,NaN,NaN,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '82230857.0')",Godsunchained,Games
4,NaN,40925443.0,0xa892b3569dc8e6b3c7db93aade62372637ebbc61fb63...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0x2c00d05ff7ffe93d77145dfe12aa56e622ae6f40,NaN,https://card.godsunchained.com/?id=62&q=4,NaN,NaN,...,NaN,NaN,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:58:44,NaN,"('Godsunchained', '40925443.0')",Godsunchained,Games

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Smart_contract            0 non-null      float64
 1   ID_token                  1000 non-null   float64
 2   Transaction_hash          1000 non-null   object
 3   Seller_address            1000 non-null   object
 4   Seller_username           0 non-null      float64
 5   Buyer_address             1000 non-null   object
 6   Buyer_username            0 non-null      float64
 7   Image_url_1               1000 non-null   object
 8   Image_url_2               0 non-null      float64
 9   Image_url_3               0 non-null      float64
 10  Image_url_4               0 non-null      float64
 11  Price_Crypto              1000 non-null   float64
 12  Crypto                    1000 non-null   object
 13  Price_USD                 1000 non-null   float64
 14  Name                      0 non-null      float64
 15  Description               0 non-null      float64
 16  Collection                1000 non-null   object
 17  Market                    1000 non-null   object
 18  Datetime_updated          1000 non-null   object
 19  Datetime_updated_seconds  1000 non-null   object
 20  Permanent_link            0 non-null      float64
 21  Unique_id_collection      1000 non-null   object
 22  Collection_cleaned        1000 non-null   object
 23  Category                  1000 non-null   object
dtypes: float64(12), object(12)
memory usage: 187.6+ KB

In [11]:
dataset.iloc[1,2]

'0xbc8412594ffa7382e8306215ece5b4e041fc641b18133221925a4ac6ecf15432'

In [7]:
# def cluster_value_counts(df, column="Buyer_address", clusters=10):
#     df = pd.DataFrame(df)
#     df[column].value_counts()

df = dataset["Buyer_address"].value_counts(normalize=True)

df

0xe0fb7622091e3d9ef9b438471b10b9ea88c7cf6b    0.279
0x61603b1cbed9879045e02ffcf17f8a0148d76f4c    0.124
0xf604d313a43f87b7d19de1477c9cc4a2c9d7ea8e    0.088
0x459a5af4fae179425a0bf9b2c4717f4b214207fc    0.040
0xab88432dcca57d5ff22e9cc6b932b1221001284b    0.032
                                              ...
0x25630ec9b58583f23b785e5bbc206fee0d958a9d    0.001
0x876036fdfbad4c60a79eb0e3742f4ac8bcf4851d    0.001
0x67b1dc6989320e65f6578adfedf0d044ff4f823f    0.001
0x98278dc211c50c07d0fdd65365cdbccec0f176d8    0.001
0x23eebb090c430783bf0665478ea6d5793b44a3c3    0.001
Name: Buyer_address, Length: 107, dtype: float64