In [1]:
import pandas as pd
import sqlite3

# Create a SQL connection to our SQLite database
con = sqlite3.connect("../DataOtherSources/EthereumNFTs/nfts.sqlite")

cur = con.cursor()
currentOwners = pd.read_sql_query("SELECT * from current_owners", con)
# print(df.head(10))
# Be sure to close the connection
con.close()

In [2]:
currentOwners

,nft_address,token_id,owner
0,0x00000000000b7F8E8E8Ad148f9d53303Bfe20796,0,0xb776cAb26B9e6Be821842DC0cc0e8217489a4581
1,0x00000000000b7F8E8E8Ad148f9d53303Bfe20796,1,0x8A73024B39A4477a5Dc43fD6360e446851AD1D28
2,0x00000000000b7F8E8E8Ad148f9d53303Bfe20796,10,0x5e5C817E9264B46cBBB980198684Ad9d14f3e0B4
3,0x00000000000b7F8E8E8Ad148f9d53303Bfe20796,11,0x8376f63c13b99D3eedfA51ddd77Ff375279B3Ba0
4,0x00000000000b7F8E8E8Ad148f9d53303Bfe20796,12,0xb5e34552F32BA9226C987769BF6555a538510BA8
...,...,...,...
7020945,0xff9315c2c4c0208Edb5152F4c4eBec75e74010c5,92,0x5d2e561a59B5AB7DA7ff9551502515CcDc9293d8
7020946,0xff9315c2c4c0208Edb5152F4c4eBec75e74010c5,98,0x052C65c1907eAD540C218648D4506760638D712b
7020947,0xffC6c59F34Cd9f8861012FDDd0c7F1323082Ab86,1,0x696B1c501c339f7057A0B58d730f2e5614f1CE7d
7020948,0xffCb352Fb3FdbEAab3F662378db28B8D151f210c,0,0x885fA6798114F28507977a07Ef122222B9dC74dD
7020949,0xffCb352Fb3FdbEAab3F662378db28B8D151f210c,1,0x885fA6798114F28507977a07Ef122222B9dC74dD

In [4]:
grouped = currentOwners.groupby("nft_address")

In [7]:
import numpy as np
from math import log2

entropyDictionary = {}

def entropy(labels):
    #.....................................
    uniqueLabels = np.unique(labels, return_counts=True)
    totalSumProbabilities = 0
    listLength = len(labels)
    for variableCount in uniqueLabels[1]:
        label_Probability = variableCount / (listLength)
        label_Entropy = label_Probability * log2(label_Probability)
        totalSumProbabilities += label_Entropy
    # print(-totalSumProbabilities)
    return -totalSumProbabilities


for (nftName, groupobject) in grouped.__iter__():
        entropyScore = entropy(groupobject["owner"])
        entropyDictionary[nftName] = entropyScore

In [9]:
import pickle
a_file = open("entropyDictionary.pkl", "wb")
pickle.dump(entropyDictionary, a_file)
a_file.close()